---
stages:
- name: Deploy
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Deploy
    type: deployer
    script: |
      #!/bin/bash
      cf push "${CF_APP}"
